USE [master]
GO

/****** Object:  Database [Salesforce_DBAmpAdHoc]    Script Date: 1/6/2019 10:27:45 PM ******/
CREATE DATABASE [Salesforce_DBAmpAdHoc] ON  PRIMARY 
( NAME = N'Salesforce_DBAmpAdHoc', FILENAME = N'F:\Data\Salesforce_DBAmpAdHoc.mdf' , SIZE = 524288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 524288KB )
 LOG ON 
( NAME = N'Salesforce_DBAmpAdHoc_log', FILENAME = N'E:\Logs\Salesforce_DBAmpAdHoc_log.ldf' , SIZE = 131072KB , MAXSIZE = 2048GB , FILEGROWTH = 131072KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Salesforce_DBAmpAdHoc].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET ARITHABORT OFF 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET  MULTI_USER 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Salesforce_DBAmpAdHoc] SET  READ_WRITE 
GO


